"""
Spike Island — Waveform Generation and Visualization
=====================================================
Convert discrete spike times into continuous extracellular voltage traces.

Real extracellular electrodes record continuous voltage signals where each
action potential appears as a brief (~1-3 ms) waveform with a characteristic
shape (rapid downstroke, slower upstroke, and undershoot). This module:

- Generates realistic action potential templates
- Superimposes templates at spike times onto a time axis
- Adds configurable noise (Gaussian, 1/f pink noise)
- Renders waveform dashboards with per-neuron traces

References
----------
- Einevoll, G.T. et al. (2013). "How extracellular field potentials
  are generated by cortical neurons." Frontiers in Computational Neuroscience.
- Hadich, F.S. et al. (2020). "Synthetic neural data for machine learning."
"""

from __future__ import annotations

import numpy as np
from scipy.ndimage import gaussian_filter1d
from typing import Any


# ---------------------------------------------------------------------------
# Action potential template generation
# ---------------------------------------------------------------------------

def generate_ap_template(
    dt_ms: float = 0.1,
    duration_ms: float = 2.0,
    peak_amplitude_mv: float = -3.0,
    undershoot_amplitude_mv: float = 1.0,
    peak_time_ms: float = 0.5,
    undershoot_time_ms: float = 1.2,
    upslope_sigma: float = 0.08,
    downslope_sigma: float = 0.15,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate a biphasic action potential template.

    The template is constructed from two Gaussians: a fast downstroke
    (negative deflection) and a slower upstroke (positive undershoot).
    This approximates the signature of a typical extracellular spike
    recorded from an LFP electrode.

    Parameters
    ----------
    dt_ms : float
        Sampling interval in milliseconds (default 0.1 ms → 10 kHz sampling).
    duration_ms : float
        Total template duration in milliseconds.
    peak_amplitude_mv : float
        Peak negative amplitude in millivolts (default -3.0 mV).
    undershoot_amplitude_mv : float
        Positive undershoot amplitude in millivolts (default 1.0 mV).
    peak_time_ms : float
        Time of the downstroke peak relative to spike onset (ms).
    undershoot_time_ms : float
        Time of the upstroke peak relative to spike onset (ms).
    upslope_sigma : float
        Gaussian sigma (in fractional time 0-1) for the downstroke.
    downslope_sigma : float
        Gaussian sigma for the upstroke.

    Returns
    -------
    times : np.ndarray
        Time axis in milliseconds (length N).
    voltage : np.ndarray
        Template voltage in millivolts (length N).

    Notes
    -----
    The template is zero-padded before and after the action potential
    to make convolution-based superposition clean.
    """
    t = np.arange(0.0, duration_ms, dt_ms)

    # Normalized time fractions (0 = onset, 1 = end)
    f = t / duration_ms

    # Downstroke (fast Gaussian centered at peak_time)
    peak_f = peak_time_ms / duration_ms
    downstroke = peak_amplitude_mv * np.exp(
        -0.5 * ((f - peak_f) / upslope_sigma) ** 2
    )

    # Upstroke (slower Gaussian centered at undershoot_time)
    under_f = undershoot_time_ms / duration_ms
    upstroke = undershoot_amplitude_mv * np.exp(
        -0.5 * ((f - under_f) / downslope_sigma) ** 2
    )

    voltage = downstroke + upstroke
    # Ensure clean edges for convolution
    voltage[0] = 0.0
    voltage[-1] = 0.0
    return t, voltage


def generate_triphasic_template(
    dt_ms: float = 0.1,
    duration_ms: float = 3.0,
    peak_amplitude_mv: float = -4.0,
    second_peak_amplitude_mv: float = 0.5,
    t1_ms: float = 0.4,
    t2_ms: float = 1.0,
    t3_ms: float = 2.0,
    sigma: float = 0.1,
) -> tuple[np.ndarray, np.ndarray]:
    """Generate a triphasic action potential template.

    Some electrode configurations (e.g., tetrodes) produce triphasic
    waveforms with a second negative peak after the upstroke.

    Parameters
    ----------
    dt_ms : float
        Sampling interval in milliseconds.
    duration_ms : float
        Total template duration in milliseconds.
    peak_amplitude_mv : float
        Amplitude of the first (primary) negative peak.
    second_peak_amplitude_mv : float
        Amplitude of the second negative peak.
    t1_ms, t2_ms, t3_ms : float
        Timing of the three phases (first downstroke, upstroke, second downstroke).
    sigma : float
        Gaussian sigma (fractional time) for all three peaks.

    Returns
    -------
    times : np.ndarray
        Time axis in milliseconds.
    voltage : np.ndarray
        Template voltage in millivolts.
    """
    t = np.arange(0.0, duration_ms, dt_ms)
    f = t / duration_ms

    def gaussian_peak(amp: float, center_ms: float, sigma_frac: float) -> np.ndarray:
        center_f = center_ms / duration_ms
        return amp * np.exp(-0.5 * ((f - center_f) / sigma_frac) ** 2)

    voltage = (
        gaussian_peak(peak_amplitude_mv, t1_ms, sigma)
        + gaussian_peak(-abs(second_peak_amplitude_mv), t2_ms, sigma * 1.2)
        + gaussian_peak(second_peak_amplitude_mv * 0.3, t3_ms, sigma)
    )

    # Ensure clean edges
    voltage[0] = 0.0
    voltage[-1] = 0.0

    return t, voltage


# ---------------------------------------------------------------------------
# Spike-to-waveform conversion
# ---------------------------------------------------------------------------

def spikes_to_waveform(
    spike_times: np.ndarray,
    template: np.ndarray,
    template_dt: float = 0.1,
    duration_ms: float = 5_000.0,
    sampling_hz: float = 10_000.0,
    noise_std_mv: float = 0.0,
    noise_type: str = "gaussian",
    seed: int | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Convert discrete spike times into a continuous voltage trace.

    Each spike is represented by superimposing the template waveform
    at the corresponding spike time on a zero-baseline signal.

    Parameters
    ----------
    spike_times : np.ndarray
        Sorted spike times in milliseconds.
    template : np.ndarray
        Voltage template in millivolts (from :func:`generate_ap_template`
        or :func:`generate_triphasic_template`).
    template_dt : float
        Sampling interval of the template in ms.
    duration_ms : float
        Total trace duration in milliseconds.
    sampling_hz : float
        Output sampling rate in Hz (default 10 kHz → 0.1 ms bins).
    noise_std_mv : float
        Standard deviation of additive noise in mV (default 0).
    noise_type : str
        Noise model: "gaussian" (white) or "pink" (1/f).
    seed : int or None
        Random seed for noise generation.

    Returns
    -------
    times : np.ndarray
        Time axis in milliseconds.
    voltage : np.ndarray
        Continuous voltage trace in millivolts.

    Notes
    -----
    Uses :func:`scipy.ndimage.convolve` under the hood for efficient
    template superposition. The spike train is binned at the template
    resolution then convolved with the template.
    """
    from scipy.ndimage import convolve1d

    rng = np.random.default_rng(seed)

    # Output time axis (convert Hz → ms)
    output_dt_ms = 1000.0 / sampling_hz
    times = np.arange(0.0, duration_ms, output_dt_ms)

    # Create a binned spike train at template resolution
    template_bins = len(template)
    bin_width = template_dt
    n_bins = int(np.ceil(duration_ms / bin_width))
    spike_train = np.zeros(n_bins, dtype=np.float64)

    # Map spike times to bins
    if len(spike_times) > 0:
        bin_indices = np.floor(spike_times / bin_width).astype(int)
        bin_indices = np.clip(bin_indices, 0, n_bins - 1)
        spike_train[bin_indices] = 1.0

    # Convolve with template (template is normalized to its peak)
    # This superimposes the template at each spike time
    if n_bins < template_bins:
        spike_train = np.pad(spike_train, (0, template_bins - n_bins))
        convolved = convolve1d(spike_train, template, mode="constant")
        convolved = convolved[:n_bins]
    else:
        convolved = convolve1d(spike_train, template, mode="constant")

    # Resample to output sampling rate if needed
    if output_dt_ms != bin_width:
        # Interpolate using linear method
        convolved_times = np.arange(0.0, len(convolved) * bin_width, bin_width)
        voltage = np.interp(times, convolved_times[:len(convolved)], convolved)
    else:
        voltage = convolved[: len(times)]

    # Add noise
    if noise_std_mv > 0:
        if noise_type == "gaussian":
            noise = rng.normal(0, noise_std_mv, size=len(times))
        elif noise_type == "pink":
            noise = _generate_pink_noise(len(times), rng) * noise_std_mv
        else:
            raise ValueError(f"Unknown noise_type: {noise_type}")
        voltage += noise

    return times, voltage


def _generate_pink_noise(length: int, rng: np.random.Generator) -> np.ndarray:
    """Generate 1/f (pink) noise using FFT filtering.

    Pink noise has a power spectral density proportional to 1/f,
    which approximates the background noise characteristics of
    neural recordings (thermal noise + physiological background).

    Parameters
    ----------
    length : int
        Number of samples.
    rng : np.random.Generator
        Random number generator.

    Returns
    -------
    np.ndarray
        Pink noise samples (zero-mean).
    """
    white = rng.normal(0, 1, size=2 * length)
    fft = np.fft.fft(white)
    # 1/f power spectrum → 1/sqrt(f) amplitude spectrum
    n_freqs = len(fft)
    freqs = np.fft.fftfreq(n_freqs)
    # Avoid division by zero at DC
    pink_spectrum = fft / (np.abs(freqs) + 1.0) ** 0.5
    # Apply a low-pass to remove DC and very high freq artifacts
    low_pass = np.ones(n_freqs)
    dc_idx = 0
    nyquist_idx = n_freqs // 2
    low_pass[dc_idx] = 0.0  # remove DC
    pink_filtered = pink_spectrum * low_pass
    result = np.fft.ifft(pink_filtered).real[:length]
    return result


# ---------------------------------------------------------------------------
# Waveform dashboard
# ---------------------------------------------------------------------------

def plot_waveform_dashboard(
    results: list[dict],
    duration_ms: float = 5_000.0,
    template: np.ndarray | None = None,
    template_dt: float = 0.1,
    sampling_hz: float = 10_000.0,
    noise_std_mv: float = 0.05,
    noise_type: str = "gaussian",
    seed: int = 42,
    save_path: str = "plots/waveform_dashboard.png",
    window_ms: float = 500.0,
) -> None:
    """Plot waveform traces for each neuron with spike raster and template.

    Generates a dashboard showing:
    - Row 1: Template waveform (the AP shape used)
    - Per neuron: Continuous voltage trace with a zoomed-in window
    - Per neuron: Spike raster aligned with the trace

    Parameters
    ----------
    results : list[dict]
        Analysis results from :func:`spike_island.analysis.analyze`,
        each containing at minimum 'name' and the original spike_times.
        Each dict should have a 'spike_times' key (np.ndarray of spike times in ms).
    duration_ms : float
        Total simulation duration in ms.
    template : np.ndarray or None
        AP template voltages. If None, generates a default biphasic template.
    template_dt : float
        Template sampling interval in ms.
    sampling_hz : float
        Output waveform sampling rate in Hz.
    noise_std_mv : float
        Noise standard deviation in mV.
    noise_type : str
        "gaussian" or "pink" noise.
    seed : int
        Random seed for noise generation.
    save_path : str
        Output PNG path.
    window_ms : float
        Duration of the zoomed-in waveform window shown per neuron.

    Notes
    -----
    This is the core visualization for showing what extracellular recordings
    look like for different firing patterns. The voltage traces reveal
    burst structure, regularity, and noise characteristics that ISI analysis
    alone cannot capture.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    # Generate default template if not provided
    if template is None:
        _, template = generate_ap_template(
            dt_ms=0.1,
            duration_ms=2.0,
            peak_amplitude_mv=-3.0,
            undershoot_amplitude_mv=1.0,
        )

    # Color palette for neurons
    colors = ["#1e3a5f", "#c45533", "#2d7d46", "#9b59b6", "#e67e22", "#1abc9c"]
    n = len(results)

    fig_height = 1.5 + 2.0 * n  # template row + 2 rows per neuron
    fig = plt.figure(figsize=(12, fig_height))

    # Row 0: Template
    total_rows = 1 + 2 * n
    template_ax = fig.add_subplot(total_rows, 1, 1)
    _, template_t = generate_ap_template()
    template_ax.plot(template_t, template, color="#222", linewidth=1.5)
    template_ax.set_ylabel("Voltage (mV)", fontsize=9)
    template_ax.set_xlabel("Time (ms)", fontsize=9)
    template_ax.set_title("AP Template", fontsize=9, fontweight="bold")
    template_ax.fill_between(template_t, template, alpha=0.2)
    template_ax.axhline(0, color="#ccc", linewidth=0.5)

    for i, res in enumerate(results):
        color = colors[i % len(colors)]
        name = res.get("name", f"Neuron {i + 1}")

        # Get spike times from result
        spike_times = res.get("spike_times", np.array([]))

        # Generate waveform
        times, voltage = spikes_to_waveform(
            spike_times,
            template,
            template_dt=template_dt,
            duration_ms=duration_ms,
            sampling_hz=sampling_hz,
            noise_std_mv=noise_std_mv,
            noise_type=noise_type,
            seed=seed + i + 1,
        )

        # Find a window with interesting activity
        if len(spike_times) >= 2:
            # Pick a window around the middle spike(s)
            mid_spike = spike_times[len(spike_times) // 2]
            t_start = max(0.0, mid_spike - window_ms / 2)
            t_end = t_start + window_ms
        else:
            t_start = 0.0
            t_end = min(window_ms, duration_ms)

        # Waveform trace (zoomed window) — row 2+2*i (1-indexed)
        trace_row = 2 + 2 * i
        trace_ax = fig.add_subplot(total_rows, 1, trace_row)
        mask = (times >= t_start) & (times < t_end)
        trace_ax.plot(times[mask] - t_start, voltage[mask], color=color, linewidth=0.6)
        trace_ax.set_ylabel("Voltage (mV)", fontsize=8)
        trace_ax.set_xlabel(f"Time (ms) — {name}", fontsize=8)
        trace_ax.set_ylim(-5, 5)
        trace_ax.axhline(0, color="#eee", linewidth=0.5)

        # Mark spike times in the window
        window_spikes = spike_times[(spike_times >= t_start) & (spike_times < t_end)]
        for st in window_spikes:
            trace_ax.axvline(st - t_start, color=color, alpha=0.3, linewidth=0.5, linestyle="--")

        # Raster — row 3+2*i
        raster_row = 3 + 2 * i
        raster_ax = fig.add_subplot(total_rows, 1, raster_row, sharex=trace_ax)
        for st in spike_times:
            adjusted = st - t_start
            if 0 <= adjusted < window_ms:
                raster_ax.plot([adjusted, adjusted], [0, 1], color=color, linewidth=1.2)
        raster_ax.set_xlim(0, window_ms)
        raster_ax.set_ylim(-0.1, 1.2)
        raster_ax.set_xticks([])
        raster_ax.set_yticks([])

    fig.suptitle(
        f"Waveform Dashboard — {n} neuron(s) · {sampling_hz/1000:.0f} kHz sampling",
        fontsize=12,
        fontweight="bold",
        y=0.98,
    )
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(save_path, dpi=150)
    print(f"Waveform dashboard saved to {save_path}")


# ---------------------------------------------------------------------------
# Utility: compute waveform statistics
# ---------------------------------------------------------------------------

def waveform_statistics(
    voltage: np.ndarray,
    times: np.ndarray | None = None,
) -> dict[str, Any]:
    """Compute summary statistics from a voltage trace.

    Parameters
    ----------
    voltage : np.ndarray
        Voltage trace in millivolts.
    times : np.ndarray or None
        Corresponding time axis in milliseconds.

    Returns
    -------
    dict
        Statistics dictionary with keys:
        - ``rms_mv``: RMS voltage
        - ``peak_to_peak_mv``: Peak-to-peak amplitude
        - ``max_mv``: Maximum voltage
        - ``min_mv``: Minimum voltage
        - ``snr_db``: Signal-to-noise ratio (signal = template peaks, noise = baseline)
        - ``mean_voltage_mv``: Mean voltage (should be near 0 for balanced traces)
        - ``duration_ms``: Trace duration in ms
        - ``samples``: Number of samples
    """
    rms = float(np.sqrt(np.mean(voltage ** 2)))
    peak_to_peak = float(np.max(voltage) - np.min(voltage))
    mean_v = float(np.mean(voltage))
    duration = float(times[-1] - times[0]) if times is not None and len(times) > 1 else 0.0

    # SNR: estimate signal power from peaks, noise from baseline
    abs_voltage = np.abs(voltage)
    # Baseline: values below 20th percentile (likely noise-only regions)
    threshold = np.percentile(abs_voltage, 20)
    baseline_mask = abs_voltage < threshold
    if np.sum(baseline_mask) > 10:
        noise_power = float(np.mean(voltage[baseline_mask] ** 2))
    else:
        noise_power = float(np.std(voltage) ** 2)

    signal_power = max(rms ** 2 - noise_power, 0.0)
    if noise_power > 0:
        snr_db = 10.0 * np.log10(signal_power / noise_power + 1e-10)
    else:
        snr_db = float("inf")

    return {
        "rms_mv": rms,
        "peak_to_peak_mv": peak_to_peak,
        "max_mv": float(np.max(voltage)),
        "min_mv": float(np.min(voltage)),
        "mean_voltage_mv": mean_v,
        "snr_db": float(snr_db),
        "duration_ms": duration,
        "samples": len(voltage),
    }


def detect_spikes_from_waveform(
    voltage: np.ndarray,
    threshold_mv: float | None = None,
) -> np.ndarray:
    """Detect spike events from a continuous voltage trace.

    Uses a threshold-based detector: finds local minima below a threshold.
    This is the simplest (and most common) spike detection method used in
    extracellular recordings.

    Parameters
    ----------
    voltage : np.ndarray
        Voltage trace in millivolts.
    threshold_mv : float or None
        Voltage threshold for detection. Defaults to 3× the
        standard deviation of the absolute voltage (negative direction).

    Returns
    -------
    np.ndarray
        Indices of detected spike peaks (local minima below threshold).

    Notes
    -----
    This is a simplified detector. Real spike sorting pipelines use
    more sophisticated methods (template matching, PCA projection,
    or clustering-based approaches like Kilosort). The threshold-based
    approach is included as a pedagogical baseline.

    The returned indices can be converted to times using the original
    time axis: ``times[detect_spikes_from_waveform(voltage)]``.
    """
    if threshold_mv is None:
        threshold_mv = -3.0 * np.std(voltage)

    # Find local minima
    minima = np.zeros_like(voltage, dtype=bool)
    minima[1:-1] = (voltage[1:-1] < voltage[:-2]) & (voltage[1:-1] < voltage[2:])
    minima[0] = voltage[0] < voltage[1]
    minima[-1] = voltage[-1] < voltage[-2]

    # Keep minima below threshold
    below_threshold = voltage < threshold_mv
    spike_indices = np.where(minima & below_threshold)[0]

    # Refractory filtering: keep only the deepest spike within 2 ms windows
    if len(spike_indices) > 1:
        keep = [spike_indices[0]]
        for idx in spike_indices[1:]:
            if idx - keep[-1] > 20:  # ~2 ms at 10 kHz sampling
                keep.append(idx)
        spike_indices = np.array(keep)

    return spike_indices
